/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_filter_ConvolutionEngine */

#ifndef _Included_jni_filter_ConvolutionEngine
#define _Included_jni_filter_ConvolutionEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_filter_ConvolutionEngine
 * Method:    convolveNative
 * Signature: ([III[III)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_filter_ConvolutionEngine_convolveNative
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray, jint, jint);

/*
 * Class:     jni_filter_ConvolutionEngine
 * Method:    convolveNativeDiff
 * Signature: ([III[III)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_filter_ConvolutionEngine_convolveNativeDiff
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
